string nomedapocao;
Console.WriteLine("Diga os três ingredientes da poção maluca");
string ingrediente1 = Console.ReadLine();
string ingrediente2 = Console.ReadLine();
string ingrediente3 = Console.ReadLine();
Console.WriteLine("Qual o nome da poção?");
nomedapocao = Console.ReadLine();
Console.WriteLine("Receita da poção " + nomedapocao);
Console.WriteLine("Adicione " + ingrediente1);
Console.WriteLine("Misture com " + ingrediente2);
Console.WriteLine("Finalize com uma pitada de " + ingrediente3);
Console.WriteLine("Sua poção " + nomedapocao + " está pronta!");
