Console.WriteLine("Máquina de Doces Simulada");
Console.WriteLine("chocolate = 25");
int n29 = 25;
Console.WriteLine("bala = 24");
int n30 = 24;
Console.WriteLine("chiclete = 23");
int n31 = 23;
Console.WriteLine("Quantos chocolates? ");
int n32 = int.Parse(Console.ReadLine());
Console.WriteLine("subtotal chocolate: " + (n29 * n32));
Console.WriteLine("Quantas balas? ");
int n33 = int.Parse(Console.ReadLine());
Console.WriteLine("subtotal bala: " + (n30 * n33));
Console.WriteLine("Quantos chicletes? ");
int n34 = int.Parse(Console.ReadLine());
Console.WriteLine("subtotal chiclete: " + (n31 * n34));
Console.WriteLine("Total: " + (n29 * n32 + n30 * n33 + n31 * n34));
